### ISSUE TITLE
Technology

### ISSUE THREAD

**Issue by filipzava** [GeoSmartCity-CIP/gsc-client#1]
Geoadmin uses OpenLayers3, AngularJS, Bootstrap. These technolegies we can also use. Please tell me what is added value of geoadmin?

**Comment by lol2x** [comment]
I had exactly same question yesterday, do we really need to use geoadmin if things achieved with it (as long as there is nothing really special and uniqe in geoadmin which I dont known) can be also achieved in other (simpler/better known) way

**Comment by eirikcsak** [comment]
Geoadmin is just another GIS web app built on the mentioned technologies. There's really no added value of using geoadmin besides some of the pilots that requires advanced GIS functionalities like layer manager, legend, draw/measure and printing _might_ be build faster using geoadmin rather than starting from scratch.

The core javascript library created through gsc will/should have no bindings to geoadmin, I suggest leaving the decision on whether or not using geoadmin to the responsible partners of each app/client consuming the library.

**Comment by pgcipriano** [comment]
Agree with Eirik.
As defined in the draft notes from the Bologna meeting (circulated to participants) gsc.js libraries will be extension of and coupled with OpenLayers3, and used in geoadmin.
Therefore, gsc.js libraries shall NOT be tightly coupled with geoadmin. 

Nevertheless, we need to understand how to catalogue information in geoadmin instances.
Actions agreed in Bologna:
1) AVINET will deploy the first instance of geoadmin
2) SINERGIS will host 
3) VMM to provide brief document/wiki/link about 
4) VMM to support  AVINET and SINERGIS in detailing geoadmin and js dependencies in deployment diagram

**Comment by jruizaranguren** [comment]
`OpenLayers3`, `AngularJS` and `Bootstrap` are libraries. `geoAdmin` is a working, tested and deployed in production GIS web app. So we are comparing apples and oranges. 

@eirikcsak,  I don't feel comfortable favouring the maximum possible number of client apps both from a software engineering and a costs and management point of view. Unless mandatory (existing proprietary clients, etc.) I would try just the opposite. 

My simpathy for _geoadmin whenever it makes sense_ comes from the following facts:
- A decent percentage of needed standard GIS-client requirements are already done. **Done!**
- It is production-ready, performant, well tested and documented.
- We can bound the amount of effort needed to get it working (VMM).
- We have experience using it and it is going to be used for at least 1 partner (VMM).
- It allow us to demonstrate a couple of GSC scenarios in the same environment (unless we like the message that we need to build a specialized client app for each use case).
- It allows us to scale in functionality in the near future. 
- geoadmin will be improving after GSC project ends.

We are happy with any alternative that fits more or less with these (and the rest of the Geosmartcity) constraints. You can change **Done!** for **We will do it** :wink:.

I also agree that gsc.js being depedency free from geoadmin UI and [geoadmin API](https://github.com/geoadmin/mf-chsdi3) can be a desirable outcome. But we also have to justify the additional value _a new API in the space_ provides, and other users don't say, Why don't we just use  `OpenLayers3`, `AngularJS` and `Bootstrap` if `gsc.js` is just that! :smiling_imp:

**Comment by filipzava** [comment]
OK, I understand. That is THE answer to my questiom ;).

**Comment by svanmieghem** [comment]
I agree completely with Javier.
