### ISSUE TITLE
Shared configuration section for library

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-client#16]
Need a place to configure the instance of the GSC data catalogue that the current script is working against.

Need a place to configure a proxy to access GSC data catalogue services that do not implement CORS in scenarios where the application is running on a different server than the catalogue

```
gsc.config.setProxy() / getProxy()
gsc.config.setDataCatalogueURL() / getDataCatalogueURL()
```

**Comment by filipzava** [comment]
Hi Runar, could you please provide example (another project solution) for proxy functionality, thanks!
